select * from orders


1. Calculate the total revenue generated from all orders?
--Total Revenue

SELECT 
    SUM(sale_price*quantity) AS total_revenue
FROM orders;

2. What is the total revenue generated by category?
--Total Revenue by Category

SELECT 
    category,
    SUM(sale_price*quantity) AS total_revenue
FROM orders
GROUP BY category
ORDER BY total_revenue DESC;

3. Which are the top 10 products with the highest revenue ?
--Top 5 Products by Revenue

SELECT TOP 10
    product_id,
    SUM(sale_price*quantity) AS total_revenue
FROM orders
GROUP BY product_id
ORDER BY total_revenue DESC;


4. Compare the average revenue between Standard and first class Shipping mode? 
--Average Revenue by Shipping Mode

SELECT 
    ship_mode,
    AVG(sale_price*quantity) AS avg_revenue
FROM orders
WHERE ship_mode IN ('Standard Class', 'First Class')
GROUP BY ship_mode
ORDER BY avg_revenue DESC;

5. Which 5 products have the highest revenue with discounts applied?
--Top 5 Products by Revenue (With Discounts Applied)

SELECT TOP 5
    product_id,
    SUM(sale_price*quantity) AS total_discounted_revenue
FROM orders
WHERE discount > 0
GROUP BY product_id
ORDER BY total_discounted_revenue DESC;

6. What are the top 3 most profitable products within each category?
--Top 3 Most Profitable Products per Category

WITH product_profit AS (
    SELECT
        category,
        product_id,
        SUM(profit) AS total_profit
    FROM orders
    GROUP BY category, product_id
)
SELECT
    category,
    product_id,
    total_profit
FROM (
    SELECT
        category,
        product_id,
        total_profit,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY total_profit DESC
        ) AS rn
    FROM product_profit
) ranked
WHERE rn <= 3
ORDER BY category, total_profit DESC;

7. Generate a report showing the total revenue for each month, ordered chronologically.
--Monthly Sales Trends:Total revenue by month, ordered chronologically.

SELECT 
    YEAR(order_date) AS sales_year,
    MONTH(order_date) AS sales_month,
    SUM(sale_price*quantity) AS total_revenue
FROM orders
GROUP BY 
    YEAR(order_date),
    MONTH(order_date)
ORDER BY 
    sales_year,
    sales_month;

8. Find top 5 highest profit generating products?

SELECT TOP 5
    product_id,
    SUM(profit) AS total_profit
FROM orders
GROUP BY product_id
ORDER BY total_profit DESC;

9. Find month over month growth comparison for 2022 and 2023 sales?
--Month-over-Month Sales Comparison (2022 vs 2023)

WITH monthly_sales AS (
    SELECT
        YEAR(order_date) AS order_year,
        MONTH(order_date) AS order_month,
        SUM(sale_price) AS total_sales
    FROM orders
    WHERE YEAR(order_date) IN (2022, 2023)
    GROUP BY 
        YEAR(order_date),
        MONTH(order_date)
)
SELECT
    order_month,
    SUM(CASE WHEN order_year = 2022 THEN total_sales ELSE 0 END) AS sales_2022,
    SUM(CASE WHEN order_year = 2023 THEN total_sales ELSE 0 END) AS sales_2023,
    -- Year-over-Year Growth %
    ROUND(
        (SUM(CASE WHEN order_year = 2023 THEN total_sales ELSE 0 END)
       - SUM(CASE WHEN order_year = 2022 THEN total_sales ELSE 0 END))
       * 100.0
       / NULLIF(SUM(CASE WHEN order_year = 2022 THEN total_sales ELSE 0 END), 0),
       2
    ) AS yoy_growth_pct
FROM monthly_sales
GROUP BY order_month
ORDER BY order_month;


10. Which month had highest sales for each category?
--Highest Sales Month per Category

WITH category_month_sales AS (
    SELECT
        category,
        YEAR(order_date) AS order_year,
        MONTH(order_date) AS order_month,
        SUM(sale_price) AS total_sales
    FROM orders
    GROUP BY 
        category,
        YEAR(order_date),
        MONTH(order_date)
)
SELECT
    category,
    order_year,
    order_month,
    total_sales
FROM (
    SELECT
        category,
        order_year,
        order_month,
        total_sales,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY total_sales DESC
        ) AS rn
    FROM category_month_sales
) ranked
WHERE rn = 1
ORDER BY category;
